[FEAT] Add Safety security test to huskyCI API

diff --git a/api/config.yaml b/api/config.yaml
--- a/api/config.yaml
+++ b/api/config.yaml
@@ -109,3 +109,30 @@ retirejs:
   language: JavaScript
   default: true
   timeOutInSeconds: 360
+
+  safety:
+  name: safety
+  image: huskyci/safety
+  cmd: |+
+    mkdir -p ~/.ssh &&
+    echo 'GIT_PRIVATE_SSH_KEY' > ~/.ssh/huskyci_id_rsa &&
+    chmod 600 ~/.ssh/huskyci_id_rsa &&
+    echo "IdentityFile ~/.ssh/huskyci_id_rsa" >> /etc/ssh/ssh_config &&
+    echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config &&
+    git clone -b %GIT_BRANCH% --single-branch %GIT_REPO% code --quiet 2> /tmp/errorGitCloneSafety
+    if [ $? -eq 0 ]; then
+      cd code
+      cat *requirements* | grep '==' > safety_analysis_requirements.txt
+      if [ $? -eq 0 ]; then
+        safety check -r safety_analysis_requirements.txt --json > safety_analysis_output.json
+        cat safety_analysis_output.json
+      else
+        echo "ERROR_REQ_NOT_FOUND"
+      fi
+    else
+      echo "ERROR_CLONING"
+      cat /tmp/errorGitCloneSafety
+    fi
+  language: Python
+  default: true
+  timeOutInSeconds: 180
