Fix HuskyCI execution should fail gracefully (#354)
* client|FIX: get error string from mongodb

Now gets the error from mongodb to print in our summary

* api|REFACT: analysis creation and validation

* api|FIX: analysis locked after execution error

Errors held analyses in a running state and were preventing new analyses
from executing.

* api|STYLE: remove comments

diff --git a/api/config.yaml b/api/config.yaml
--- a/api/config.yaml
+++ b/api/config.yaml
@@ -200,7 +200,13 @@ yarnaudit:
       cd code
       if [ -f yarn.lock ]; then
         yarn audit --json > /tmp/results.json 2> /tmp/errorYarnAudit
-        jq -c -M -j --slurp '{advisories: (. | map(select(.type == "auditAdvisory") | .data.advisory)), metadata: (. | map(select(.type == "auditSummary") | .data) | add)}' /tmp/results.json
+        if [ $? -eq 0 ]; then
+          jq -c -M -j --slurp '{advisories: (. | map(select(.type == "auditAdvisory") | .data.advisory)), metadata: (. | map(select(.type == "auditSummary") | .data) | add)}' /tmp/results.json > /tmp/output.json
+          cat /tmp/output.json
+        else
+          echo -n 'ERROR_RUNNING_YARN_AUDIT - '
+          cat /tmp/errorYarnAudit
+        fi
       else
         echo 'ERROR_YARN_LOCK_NOT_FOUND'
       fi
