Modifies `api` to run Infer tests

diff --git a/api/config.yaml b/api/config.yaml
--- a/api/config.yaml
+++ b/api/config.yaml
@@ -321,6 +321,52 @@ spotbugs:
   default: false
   timeOutInSeconds: 3600
 
+infer:
+  name: infer
+  image: huskyci/infer
+  imageTag: "4.0.0-beta4"
+  cmd: |+
+    mkdir -p ~/.ssh &&
+    echo '%GIT_PRIVATE_SSH_KEY%' > ~/.ssh/huskyci_id_rsa &&
+    chmod 600 ~/.ssh/huskyci_id_rsa &&
+    echo "IdentityFile ~/.ssh/huskyci_id_rsa" >> /etc/ssh/ssh_config &&
+    echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config &&
+    GIT_TERMINAL_PROMPT=0 git clone -b %GIT_BRANCH% --single-branch %GIT_REPO% code --quiet 2> /tmp/errorGitCloneInfer
+    if [ $? -eq 0 ]; then
+       cd code
+       if [ -f "pom.xml" ]; then
+           mv ../code /tmp/code
+           cd /tmp/code
+           project_type=$(cat pom.xml|grep packaging|cut -d'<' -f2|cut -d'>' -f2)
+           infer run -- bash /usr/local/bin/mvn-entrypoint.sh 2> /tmp/errorMavenBuild 1> /dev/null
+           if [ $? -eq 0 ]; then
+               cat infer-out/report.json
+           else
+               echo "ERROR_RUNNING_MAVEN_BUILD"
+               cat /tmp/errorMavenBuild
+           fi
+       elif [ -f "build.gradle" ]; then
+           mv ../code /tmp/code
+           cd /tmp/code
+           infer run -- /opt/gradle/bin/gradle -p /tmp/code build 2> /tmp/errorGradleBuild 1> /dev/null
+            if [ $? -eq 0 ]; then
+               cat infer-out/report.json
+            else
+               echo "ERROR_RUNNING_GRADLE_BUILD"
+               cat /tmp/errorGradleBuild
+            fi
+       else
+           echo "ERROR_UNSUPPORTED_JAVA_PROJECT"
+       fi
+    else
+        echo "ERROR_CLONING"
+        cat /tmp/errorGitCloneInfer
+    fi
+  type: Language
+  language: Java
+  default: false
+  timeOutInSeconds: 3600
+
 gitleaks:
   name: gitleaks
   image: huskyci/gitleaks
