api|FIX: analysis locked after execution error
Errors held analyses in a running state and were preventing new analyses
from executing.

diff --git a/api/config.yaml b/api/config.yaml
--- a/api/config.yaml
+++ b/api/config.yaml
@@ -29,9 +29,10 @@ gitauthors:
     echo "IdentityFile ~/.ssh/huskyci_id_rsa" >> /etc/ssh/ssh_config &&
     echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config &&
     git clone %GIT_REPO% code --quiet 2> /tmp/errorGitCloneEnry
+    cd code
+    git checkout %GIT_BRANCH% --quiet
     if [ $? -eq 0 ]; then
-      cd code
-      for i in $(git log origin/master..origin/%GIT_BRANCH% --pretty="%ae" | sort -u); do
+      for i in $(git log origin/master.. --pretty="%ae" | sort -u); do
         jsonMiddle="\"$i\",$jsonMiddle"
       done
       length=${#jsonMiddle}
@@ -199,7 +200,13 @@ yarnaudit:
       cd code
       if [ -f yarn.lock ]; then
         yarn audit --json > /tmp/results.json 2> /tmp/errorYarnAudit
-        jq -c -M -j --slurp '{advisories: (. | map(select(.type == "auditAdvisory") | .data.advisory)), metadata: (. | map(select(.type == "auditSummary") | .data) | add)}' /tmp/results.json
+        if [ $? -eq 0 ]; then
+          jq -c -M -j --slurp '{advisories: (. | map(select(.type == "auditAdvisory") | .data.advisory)), metadata: (. | map(select(.type == "auditSummary") | .data) | add)}' /tmp/results.json > /tmp/output.json
+          cat /tmp/output.json
+        else
+          echo -n 'ERROR_RUNNING_YARN_AUDIT - '
+          cat /tmp/errorYarnAudit
+        fi
       else
         echo 'ERROR_YARN_LOCK_NOT_FOUND'
       fi
