api,client|FIX: Handle when Safety fails to run

diff --git a/api/config.yaml b/api/config.yaml
--- a/api/config.yaml
+++ b/api/config.yaml
@@ -141,9 +141,16 @@ safety:
     if [ $? -eq 0 ]; then
       cd code
       if [ -f requirements.txt ]; then
-        safety check -r requirements.txt --json > safety_huskyci_analysis_output.json 2> /tmp/errorUnpinnedReq
-        /script.sh safety_huskyci_analysis_output.json
-        cat output.json
+        cat requirements.txt | grep '=' | grep -v '#' 1> safety_huskyci_analysis_requirements.txt
+        safety check -r safety_huskyci_analysis_requirements.txt --json > safety_huskyci_analysis_output.json 2> /tmp/errorRunning
+        if [ $? -eq 0 ]; then
+          chmod +x /script.sh
+          /script.sh safety_huskyci_analysis_output.json
+          cat output.json
+        else
+          echo "ERROR_RUNNING_SAFETY"
+          cat /tmp/errorRunning 
+        fi
       else
         echo "ERROR_REQ_NOT_FOUND"  
       fi
