api|FEAT: add yarn audit security test
Updated config.yaml to support yarn audit
Added yarn audit to context
Added yarn audit error codes
Added yarn audit to the summary of the analysis
Added yarn audit info to security tests
Added yarn audit security test
Added yarn audit to javascriptresults

Github issue #336

diff --git a/api/config.yaml b/api/config.yaml
--- a/api/config.yaml
+++ b/api/config.yaml
@@ -178,7 +178,34 @@ npmaudit:
       fi
     else
       echo "ERROR_CLONING"
-      cat /tmp/errorGitCloneSafety
+      cat /tmp/errorGitCloneNpmAudit
+    fi
+  type: Language
+  language: JavaScript
+  default: true
+  timeOutInSeconds: 360
+
+yarnaudit:
+  name: yarnaudit
+  image: huskyci/npmaudit
+  cmd: |+
+    mkdir -p ~/.ssh &&
+    echo 'GIT_PRIVATE_SSH_KEY' > ~/.ssh/huskyci_id_rsa &&
+    chmod 600 ~/.ssh/huskyci_id_rsa &&
+    echo "IdentityFile ~/.ssh/huskyci_id_rsa" >> /etc/ssh/ssh_config &&
+    echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config &&
+    git clone -b %GIT_BRANCH% --single-branch %GIT_REPO% code --quiet 2> /tmp/errorGitCloneYarnAudit
+    if [ $? -eq 0 ]; then
+      cd code
+      if [ -f yarn.lock ]; then
+        yarn audit --json > /tmp/results.json 2> /tmp/errorYarnAudit
+        jq -c -M -j --slurp '{advisories: (. | map(select(.type == "auditAdvisory") | .data.advisory)), metadata: (. | map(select(.type == "auditSummary") | .data) | add)}' /tmp/results.json
+      else
+        echo 'ERROR_YARN_LOCK_NOT_FOUND'
+      fi
+    else
+      echo "ERROR_CLONING"
+      cat /tmp/errorGitCloneYarnAudit
     fi
   type: Language
   language: JavaScript
