api|FEAT: Add commands to run npm audit inside container

diff --git a/api/config.yaml b/api/config.yaml
--- a/api/config.yaml
+++ b/api/config.yaml
@@ -177,3 +177,29 @@ safety:
   language: Python
   default: true
   timeOutInSeconds: 360
+
+npmaudit:
+  name: npmaudit
+  image: huskyci/npmaudit
+  cmd: |+
+    mkdir -p ~/.ssh &&
+    echo 'GIT_PRIVATE_SSH_KEY' > ~/.ssh/huskyci_id_rsa &&
+    chmod 600 ~/.ssh/huskyci_id_rsa &&
+    echo "IdentityFile ~/.ssh/huskyci_id_rsa" >> /etc/ssh/ssh_config &&
+    echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config &&
+    git clone -b %GIT_BRANCH% --single-branch %GIT_REPO% code --quiet 2> /tmp/errorGitCloneNpmAudit
+    if [ $? -eq 0 ]; then
+      cd code
+      if [ -f package.json ]; then
+        npm audit --only=prod --json > /tmp/results.json
+        cat /tmp/results.json
+      else
+        echo 'ERROR_RUNNING_NPMAUDIT'
+      fi
+    else
+      echo "ERROR_CLONING"
+      cat /tmp/errorGitCloneSafety
+    fi
+  language: JavaScript
+  default: true
+  timeOutInSeconds: 360
