spotbugs for gradle projects is ready

diff --git a/api/config.yaml b/api/config.yaml
--- a/api/config.yaml
+++ b/api/config.yaml
@@ -251,7 +251,7 @@ spotbugs:
            mv ../code /usr/src/mymaven
            cd /usr/src/mymaven
            project_type=$(cat pom.xml|grep packaging|cut -d'<' -f2|cut -d'>' -f2)
-           bash /usr/local/bin/mvn-entrypoint.sh 2> /tmp/errorSpotBugsBuild 1> /dev/null
+           bash /usr/local/bin/mvn-entrypoint.sh 2> /tmp/errorMavenBuild 1> /dev/null
            if [ $? -eq 0 ]; then
                if [[ "$project_type" = "war" ]]; then
                   # WAR
@@ -264,11 +264,18 @@ spotbugs:
                fi
                java -jar /opt/spotbugs/lib/spotbugs.jar -textui -quiet -xml -exitcode -bugCategories SECURITY -exclude /opt/spotbugs/exclude.xml -pluginList /opt/findsecbugs-plugin-1.9.0.jar /usr/src/mymaven/target/needToBeScanned
            else
-               echo "ERROR_RUNNING_SPOT_BUGS"
-               cat /tmp/errorSpotBugsBuild
+               echo "ERROR_RUNNING_MAVEN_BUILD"
+               cat /tmp/errorMavenBuild
            fi
        elif [ -f "build.gradle" ]; then
-           # this is a gradle project
+           mv ../code /tmp/mygradle
+           /opt/gradle/bin/gradle -p /tmp/mygradle build 2> /tmp/errorGradleBuild 1> /dev/null
+            if [ $? -eq 0 ]; then
+               java -jar /opt/spotbugs/lib/spotbugs.jar -textui -quiet -xml -exitcode -bugCategories SECURITY -exclude /opt/spotbugs/exclude.xml -pluginList /opt/findsecbugs-plugin-1.9.0.jar /tmp/mygradle/build
+            else
+               echo "ERROR_RUNNING_GRADLE_BUILD"
+               cat /tmp/errorGradleBuild
+            fi
        elif [ -f "build.sbt" ]; then
            # this is a SBT project
        else
